title: KEY DISTRIBUTION IN CLIENT SIDE ON MULTI USER
       ENCRYPTED DATA IN CLOUD ENVIRONMENT
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/ibrahimsenan/ibrahimsenan.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Documentation
   url: /about
 - title: Future Work
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
